CREATE TABLE [Fact].[Documenti] (
    [PKDocumenti]                                     INT             CONSTRAINT [DFT_Fact_Documenti_PKDocumenti] DEFAULT (NEXT VALUE FOR [dbo].[seq_Fact_Documenti]) NOT NULL,
    [PKDataInizioEsercizio]                           DATE            NOT NULL,
    [PKDataFineEsercizio]                             DATE            NOT NULL,
    [PKDataRegistrazione]                             DATE            NOT NULL,
    [PKDataDocumento]                                 DATE            NOT NULL,
    [PKDataCompetenza]                                DATE            NOT NULL,
    [PKCliente]                                       INT             NOT NULL,
    [PKClienteFattura]                                INT             NOT NULL,
    [PKGruppoAgenti]                                  INT             NOT NULL,
    [PKCapoArea]                                      INT             NOT NULL,
    [PKDataFineContratto]                             DATE            NOT NULL,
    [PKDataInizioContratto]                           DATE            NOT NULL,
    [PKGruppoAgenti_Riga]                             INT             NOT NULL,
    [PKCapoArea_Riga]                                 INT             NOT NULL,
    [PKArticolo]                                      INT             NOT NULL,
    [PKMacroTipologia]                                INT             NOT NULL,
    [HistoricalHashKey]                               VARBINARY (20)  NULL,
    [ChangeHashKey]                                   VARBINARY (20)  NULL,
    [HistoricalHashKeyASCII]                          VARCHAR (34)    NULL,
    [ChangeHashKeyASCII]                              VARCHAR (34)    NULL,
    [InsertDatetime]                                  DATETIME        NOT NULL,
    [UpdateDatetime]                                  DATETIME        NOT NULL,
    [IsDeleted]                                       BIT             NOT NULL,
    [IDDocumento_Riga]                                INT             NOT NULL,
    [IDDocumento]                                     INT             NOT NULL,
    [IDProfilo]                                       NVARCHAR (10)   NOT NULL,
    [Profilo]                                         NVARCHAR (60)   NOT NULL,
    [TipoRegistro]                                    CHAR (2)        NOT NULL,
    [NumeroRegistro]                                  INT             NOT NULL,
    [Registro]                                        NVARCHAR (60)   NOT NULL,
    [CodiceEsercizio]                                 CHAR (4)        NOT NULL,
    [NumeroDocumento]                                 NVARCHAR (20)   NOT NULL,
    [TipoSoggettoCommerciale]                         NVARCHAR (20)   NOT NULL,
    [TipoSoggettoCommercialeFattura]                  NVARCHAR (20)   NOT NULL,
    [Libero4]                                         NVARCHAR (200)  NOT NULL,
    [IDLibero1]                                       NVARCHAR (10)   NOT NULL,
    [Libero1]                                         NVARCHAR (60)   NOT NULL,
    [IDLibero2]                                       NVARCHAR (10)   NOT NULL,
    [Libero2]                                         NVARCHAR (60)   NOT NULL,
    [IDLibero3]                                       NVARCHAR (10)   NOT NULL,
    [Libero3]                                         NVARCHAR (60)   NOT NULL,
    [IDTipoFatturazione]                              NVARCHAR (10)   NOT NULL,
    [TipoFatturazione]                                NVARCHAR (60)   NOT NULL,
    [NumeroRiga]                                      INT             NOT NULL,
    [CodiceCondizioniPagamento]                       NVARCHAR (10)   NOT NULL,
    [CondizioniPagamento]                             NVARCHAR (60)   NOT NULL,
    [RinnovoAutomatico]                               CHAR (1)        NOT NULL,
    [NoteIntestazione]                                NVARCHAR (1000) NOT NULL,
    [IsProfiloValidoPerStatisticaFatturato]           BIT             NOT NULL,
    [IsProfiloValidoPerStatisticaFatturatoFormazione] BIT             NOT NULL,
    [ImportoTotale]                                   DECIMAL (10, 2) NOT NULL,
    [ImportoProvvigioneCapoArea]                      DECIMAL (10, 2) NOT NULL,
    [ImportoProvvigioneAgente]                        DECIMAL (10, 2) NOT NULL,
    [ImportoProvvigioneSubagente]                     DECIMAL (10, 2) NOT NULL,
    [Progressivo]                                     INT             NOT NULL,
    [Quote]                                           INT             NOT NULL,
    [IDDocumento_Riga_Provenienza]                    INT             NULL,
    [NoteDecisionali]                                 NVARCHAR (1000) NOT NULL,
    [PKDataDisdetta]                                  DATE            NOT NULL,
    [IDDocumentoRinnovato]                            INT             NULL,
    CONSTRAINT [PK_Fact_Documenti] PRIMARY KEY CLUSTERED ([PKDocumenti] ASC),
    CONSTRAINT [FK_Fact_Documenti_PKArticolo] FOREIGN KEY ([PKArticolo]) REFERENCES [Dim].[Articolo] ([PKArticolo]),
    CONSTRAINT [FK_Fact_Documenti_PKCapoArea] FOREIGN KEY ([PKCapoArea]) REFERENCES [Dim].[CapoArea] ([PKCapoArea]),
    CONSTRAINT [FK_Fact_Documenti_PKCapoArea_Riga] FOREIGN KEY ([PKCapoArea_Riga]) REFERENCES [Dim].[CapoArea] ([PKCapoArea]),
    CONSTRAINT [FK_Fact_Documenti_PKCliente] FOREIGN KEY ([PKCliente]) REFERENCES [Dim].[Cliente] ([PKCliente]),
    CONSTRAINT [FK_Fact_Documenti_PKClienteFattura] FOREIGN KEY ([PKClienteFattura]) REFERENCES [Dim].[Cliente] ([PKCliente]),
    CONSTRAINT [FK_Fact_Documenti_PKDataCompetenza] FOREIGN KEY ([PKDataCompetenza]) REFERENCES [Dim].[Data] ([PKData]),
    CONSTRAINT [FK_Fact_Documenti_PKDataDocumento] FOREIGN KEY ([PKDataDocumento]) REFERENCES [Dim].[Data] ([PKData]),
    CONSTRAINT [FK_Fact_Documenti_PKDataFineContratto] FOREIGN KEY ([PKDataFineContratto]) REFERENCES [Dim].[Data] ([PKData]),
    CONSTRAINT [FK_Fact_Documenti_PKDataFineEsercizio] FOREIGN KEY ([PKDataFineEsercizio]) REFERENCES [Dim].[Data] ([PKData]),
    CONSTRAINT [FK_Fact_Documenti_PKDataInizioContratto] FOREIGN KEY ([PKDataInizioContratto]) REFERENCES [Dim].[Data] ([PKData]),
    CONSTRAINT [FK_Fact_Documenti_PKDataInizioEsercizio] FOREIGN KEY ([PKDataInizioEsercizio]) REFERENCES [Dim].[Data] ([PKData]),
    CONSTRAINT [FK_Fact_Documenti_PKDataRegistrazione] FOREIGN KEY ([PKDataRegistrazione]) REFERENCES [Dim].[Data] ([PKData]),
    CONSTRAINT [FK_Fact_Documenti_PKGruppoAgenti] FOREIGN KEY ([PKGruppoAgenti]) REFERENCES [Dim].[GruppoAgenti] ([PKGruppoAgenti]),
    CONSTRAINT [FK_Fact_Documenti_PKGruppoAgenti_Riga] FOREIGN KEY ([PKGruppoAgenti_Riga]) REFERENCES [Dim].[GruppoAgenti] ([PKGruppoAgenti]),
    CONSTRAINT [FK_Fact_Documenti_PKMacroTipologia] FOREIGN KEY ([PKMacroTipologia]) REFERENCES [Dim].[MacroTipologia] ([PKMacroTipologia])
);


GO

CREATE UNIQUE NONCLUSTERED INDEX [IX_Fact_Documenti_IDDocumento_Riga]
    ON [Fact].[Documenti]([IDDocumento_Riga] ASC);


GO

