USE [master]
GO

/****** Object:  Database [CesiDW]    Script Date: 1/17/2021 11:28:54 AM ******/
CREATE DATABASE [CesiDW]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CesiDW', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.EPISQL\MSSQL\DATA\CesiDW.mdf' , SIZE = 65536KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CesiDW_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.EPISQL\MSSQL\DATA\CesiDW_log.ldf' , SIZE = 65536KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CesiDW].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CesiDW] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CesiDW] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CesiDW] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CesiDW] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CesiDW] SET ARITHABORT OFF 
GO

ALTER DATABASE [CesiDW] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CesiDW] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CesiDW] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CesiDW] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CesiDW] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CesiDW] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CesiDW] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CesiDW] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CesiDW] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CesiDW] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CesiDW] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CesiDW] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CesiDW] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CesiDW] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CesiDW] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CesiDW] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CesiDW] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CesiDW] SET RECOVERY FULL 
GO

ALTER DATABASE [CesiDW] SET  MULTI_USER 
GO

ALTER DATABASE [CesiDW] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CesiDW] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CesiDW] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CesiDW] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CesiDW] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CesiDW] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CesiDW] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CesiDW] SET  READ_WRITE 
GO

