CREATE TABLE [Dim].[ClienteAccessi] (
    [PKClienteAccessi]                     INT            CONSTRAINT [DFT_Dim_ClienteAccessi_PKClienteAccessi] DEFAULT (NEXT VALUE FOR [dbo].[seq_Dim_ClienteAccessi]) NOT NULL,
    [Username]                             NVARCHAR (60)  NOT NULL,
    [HistoricalHashKey]                    VARBINARY (20) NULL,
    [ChangeHashKey]                        VARBINARY (20) NULL,
    [HistoricalHashKeyASCII]               VARCHAR (34)   NULL,
    [ChangeHashKeyASCII]                   VARCHAR (34)   NULL,
    [InsertDatetime]                       DATETIME       CONSTRAINT [DFT_Dim_ClienteAccessi_InsertDatetime] DEFAULT (getdate()) NOT NULL,
    [UpdateDatetime]                       DATETIME       CONSTRAINT [DFT_Dim_ClienteAccessi_UpdateDatetime] DEFAULT (getdate()) NOT NULL,
    [IsDeleted]                            BIT            CONSTRAINT [DFT_Dim_ClienteAccessi_IsDeleted] DEFAULT ((0)) NOT NULL,
    [IDSoggettoCommerciale]                INT            NULL,
    [PKCliente]                            INT            NOT NULL,
    [Email]                                NVARCHAR (120) NOT NULL,
    [IDAnagraficaCometa]                   INT            CONSTRAINT [DFT_Dim_ClienteAccessi_IDAnagraficaCometa] DEFAULT ((-1)) NOT NULL,
    [HasAnagraficaCometa]                  BIT            CONSTRAINT [DFT_Dim_ClienteAccessi_HasAnagraficaCometa] DEFAULT ((0)) NOT NULL,
    [HasAnagraficaNopCommerce]             BIT            CONSTRAINT [DFT_Dim_ClienteAccessi_HasAnagraficaNopCommerce] DEFAULT ((0)) NOT NULL,
    [HasAnagraficaMySolution]              BIT            CONSTRAINT [DFT_Dim_ClienteAccessi_HasAnagraficaMySolution] DEFAULT ((0)) NOT NULL,
    [ProvenienzaAnagrafica]                NVARCHAR (20)  CONSTRAINT [DFT_Dim_ClienteAccessi_ProvenienzaAnagrafica] DEFAULT (N'') NOT NULL,
    [CodiceCliente]                        NVARCHAR (10)  NOT NULL,
    [TipoSoggettoCommerciale]              NVARCHAR (10)  CONSTRAINT [DFT_Dim_ClienteAccessi_TipoSoggettoCommerciale] DEFAULT (N'') NOT NULL,
    [RagioneSociale]                       NVARCHAR (120) NOT NULL,
    [CodiceFiscale]                        NVARCHAR (20)  NOT NULL,
    [PartitaIVA]                           NVARCHAR (20)  NOT NULL,
    [Indirizzo]                            NVARCHAR (120) NOT NULL,
    [CAP]                                  NVARCHAR (10)  NOT NULL,
    [Localita]                             NVARCHAR (60)  NOT NULL,
    [Provincia]                            NVARCHAR (50)  NOT NULL,
    [Regione]                              NVARCHAR (60)  NOT NULL,
    [Macroregione]                         NVARCHAR (60)  NOT NULL,
    [Nazione]                              NVARCHAR (60)  NOT NULL,
    [Telefono]                             NVARCHAR (60)  NOT NULL,
    [Cellulare]                            NVARCHAR (60)  NOT NULL,
    [Fax]                                  NVARCHAR (60)  NOT NULL,
    [TipoCliente]                          NVARCHAR (10)  NOT NULL,
    [Agente]                               NVARCHAR (60)  NOT NULL,
    [PKDataInizioContratto]                DATE           CONSTRAINT [DFT_Dim_ClienteAccessi_PKInizioContratto] DEFAULT (CONVERT([date],'19000101')) NOT NULL,
    [PKDataFineContratto]                  DATE           CONSTRAINT [DFT_Dim_ClienteAccessi_PKFineContratto] DEFAULT (CONVERT([date],'19000101')) NOT NULL,
    [PKDataDisdetta]                       DATE           CONSTRAINT [DFT_Dim_ClienteAccessi_PKDataDisdetta] DEFAULT (CONVERT([date],'19000101')) NOT NULL,
    [MotivoDisdetta]                       NVARCHAR (120) NOT NULL,
    [PKGruppoAgenti]                       INT            CONSTRAINT [DFT_Dim_ClienteAccessi_PKGruppoAgenti] DEFAULT ((-1)) NOT NULL,
    [Cognome]                              NVARCHAR (60)  NOT NULL,
    [Nome]                                 NVARCHAR (60)  NOT NULL,
    [IsAttivo]                             BIT            CONSTRAINT [DFT_Dim_ClienteAccessi_IsAttivo] DEFAULT ((0)) NOT NULL,
    [IsAbbonato]                           BIT            CONSTRAINT [DFT_Dim_ClienteAccessi_IsAbbonato] DEFAULT ((0)) NOT NULL,
    [IDSoggettoCommerciale_migrazione]     INT            NULL,
    [IDSoggettoCommerciale_migrazione_old] INT            NULL,
    [IDProvincia]                          NVARCHAR (10)  NOT NULL,
    [IsClienteFormazione]                  BIT            CONSTRAINT [DFT_Dim_ClienteAccessi_IsClienteFormazione] DEFAULT ((0)) NOT NULL,
    [CapoAreaDefault]                      NVARCHAR (60)  CONSTRAINT [DFT_Dim_ClienteAccessi_CapoAreaDefault] DEFAULT (N'') NOT NULL,
    [AgenteDefault]                        NVARCHAR (60)  CONSTRAINT [DFT_Dim_ClienteAccessi_AgenteDefault] DEFAULT (N'') NOT NULL,
    [HasRoleMySolutionDemo]                BIT            CONSTRAINT [DFT_Dim_ClienteAccessi_HasRoleMySolutionDemo] DEFAULT ((0)) NOT NULL,
    [IDMySolution]                         INT            NULL,
    CONSTRAINT [PK_Dim_ClienteAccessi] PRIMARY KEY CLUSTERED ([PKClienteAccessi] ASC),
    CONSTRAINT [FK_Dim_ClienteAccessi_PKCliente] FOREIGN KEY ([PKCliente]) REFERENCES [Dim].[Cliente] ([PKCliente]),
    CONSTRAINT [FK_Dim_ClienteAccessi_PKDataDisdetta] FOREIGN KEY ([PKDataDisdetta]) REFERENCES [Dim].[Data] ([PKData]),
    CONSTRAINT [FK_Dim_ClienteAccessi_PKDataFineContratto] FOREIGN KEY ([PKDataFineContratto]) REFERENCES [Dim].[Data] ([PKData]),
    CONSTRAINT [FK_Dim_ClienteAccessi_PKDataInizioContratto] FOREIGN KEY ([PKDataInizioContratto]) REFERENCES [Dim].[Data] ([PKData]),
    CONSTRAINT [FK_Dim_ClienteAccessi_PKGruppoAgenti] FOREIGN KEY ([PKGruppoAgenti]) REFERENCES [Dim].[GruppoAgenti] ([PKGruppoAgenti])
);


GO

